// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"gyulist-api-go/configs"
	"gyulist-api-go/internal/application/services"
	"gyulist-api-go/internal/infrastructure/repositories"
	"gyulist-api-go/internal/interfaces/http/handlers"
	"gyulist-api-go/internal/interfaces/http/handlers/generated"
)

// Injectors from wire.go:

// InitializeApp はアプリケーション全体の依存性を初期化します
func InitializeApp() (*gin.Engine, error) {
	config := configs.Load()
	healthRepository := repositories.NewHealthRepository()
	healthService := services.NewHealthService(healthRepository)
	systemHandler := handlers.NewSystemHandler(config, healthService)
	engine := NewRouter(config, systemHandler)
	return engine, nil
}

// wire.go:

// NewRouter はGinルーターを作成します
func NewRouter(
	cfg *configs.Config,
	systemHandler *handlers.SystemHandler,
) *gin.Engine {

	if cfg.App.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	} else {
		gin.SetMode(gin.DebugMode)
	}

	r := gin.New()

	r.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:3000", "https://gyulist.com"},
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Length", "Content-Type", "Authorization"},
		AllowCredentials: true,
	}))
	r.Use(gin.Logger())
	r.Use(gin.Recovery())
	generated.RegisterHandlersWithOptions(r, systemHandler, generated.GinServerOptions{
		BaseURL:      "/api/v1",
		Middlewares:  nil,
		ErrorHandler: nil,
	})

	return r
}
